# -*- coding: utf-8 -*-
"""deep_learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gno3NnWRuvadtpVPwHOEVUTASPIpF1XQ
"""

import tensorflow as tf
import pandas as pd
import numpy as np

x = np.array([x for x in range(-40,40)], dtype=float)
y = np.array([(x*1.8)+32 for x in range(-40, 40)], dtype=float)


l0 = tf.keras.layers.Dense(units=1, input_shape=[1])
# l1 = tf.keras.layers.Dense(units=4)
# l2 = tf.keras.layers.Dense(units=1)

model = tf.keras.Sequential([l0])
model.compile(loss="mean_squared_error", optimizer= tf.optimizers.Adam(0.1))
histroy = model.fit(x, y, epochs=500, verbose=False)



import matplotlib.pyplot as plt
plt.xlabel("epoch number")
plt.xlabel("Loss")
plt.plot(histroy.history['loss'])

histroy.history['loss']

model.predict([100])
